//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SumForm.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://lnz/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lnz/", ConfigurationName="WS.SimpleSoap")]
    public interface SimpleSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lnz/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lnz/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int x, int y);
        
        // CODEGEN: Контракт генерации сообщений с именем s из пространства имен http://lnz/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://lnz/Concat", ReplyAction="*")]
        SumForm.WS.ConcatResponse Concat(SumForm.WS.ConcatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lnz/Concat", ReplyAction="*")]
        System.Threading.Tasks.Task<SumForm.WS.ConcatResponse> ConcatAsync(SumForm.WS.ConcatRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем a1 из пространства имен http://lnz/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://lnz/Sum", ReplyAction="*")]
        SumForm.WS.SumResponse Sum(SumForm.WS.SumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lnz/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<SumForm.WS.SumResponse> SumAsync(SumForm.WS.SumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lnz/Adds", ReplyAction="*")]
        int Adds(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lnz/Adds", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddsAsync(int x, int y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConcatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Concat", Namespace="http://lnz/", Order=0)]
        public SumForm.WS.ConcatRequestBody Body;
        
        public ConcatRequest() {
        }
        
        public ConcatRequest(SumForm.WS.ConcatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lnz/")]
    public partial class ConcatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double d;
        
        public ConcatRequestBody() {
        }
        
        public ConcatRequestBody(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConcatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConcatResponse", Namespace="http://lnz/", Order=0)]
        public SumForm.WS.ConcatResponseBody Body;
        
        public ConcatResponse() {
        }
        
        public ConcatResponse(SumForm.WS.ConcatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lnz/")]
    public partial class ConcatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConcatResult;
        
        public ConcatResponseBody() {
        }
        
        public ConcatResponseBody(string ConcatResult) {
            this.ConcatResult = ConcatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sum", Namespace="http://lnz/", Order=0)]
        public SumForm.WS.SumRequestBody Body;
        
        public SumRequest() {
        }
        
        public SumRequest(SumForm.WS.SumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lnz/")]
    public partial class SumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SumForm.WS.A a1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SumForm.WS.A a2;
        
        public SumRequestBody() {
        }
        
        public SumRequestBody(SumForm.WS.A a1, SumForm.WS.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumResponse", Namespace="http://lnz/", Order=0)]
        public SumForm.WS.SumResponseBody Body;
        
        public SumResponse() {
        }
        
        public SumResponse(SumForm.WS.SumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lnz/")]
    public partial class SumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SumForm.WS.A SumResult;
        
        public SumResponseBody() {
        }
        
        public SumResponseBody(SumForm.WS.A SumResult) {
            this.SumResult = SumResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimpleSoapChannel : SumForm.WS.SimpleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleSoapClient : System.ServiceModel.ClientBase<SumForm.WS.SimpleSoap>, SumForm.WS.SimpleSoap {
        
        public SimpleSoapClient() {
        }
        
        public SimpleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int x, int y) {
            return base.Channel.AddAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SumForm.WS.ConcatResponse SumForm.WS.SimpleSoap.Concat(SumForm.WS.ConcatRequest request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            SumForm.WS.ConcatRequest inValue = new SumForm.WS.ConcatRequest();
            inValue.Body = new SumForm.WS.ConcatRequestBody();
            inValue.Body.s = s;
            inValue.Body.d = d;
            SumForm.WS.ConcatResponse retVal = ((SumForm.WS.SimpleSoap)(this)).Concat(inValue);
            return retVal.Body.ConcatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SumForm.WS.ConcatResponse> SumForm.WS.SimpleSoap.ConcatAsync(SumForm.WS.ConcatRequest request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<SumForm.WS.ConcatResponse> ConcatAsync(string s, double d) {
            SumForm.WS.ConcatRequest inValue = new SumForm.WS.ConcatRequest();
            inValue.Body = new SumForm.WS.ConcatRequestBody();
            inValue.Body.s = s;
            inValue.Body.d = d;
            return ((SumForm.WS.SimpleSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SumForm.WS.SumResponse SumForm.WS.SimpleSoap.Sum(SumForm.WS.SumRequest request) {
            return base.Channel.Sum(request);
        }
        
        public SumForm.WS.A Sum(SumForm.WS.A a1, SumForm.WS.A a2) {
            SumForm.WS.SumRequest inValue = new SumForm.WS.SumRequest();
            inValue.Body = new SumForm.WS.SumRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            SumForm.WS.SumResponse retVal = ((SumForm.WS.SimpleSoap)(this)).Sum(inValue);
            return retVal.Body.SumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SumForm.WS.SumResponse> SumForm.WS.SimpleSoap.SumAsync(SumForm.WS.SumRequest request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<SumForm.WS.SumResponse> SumAsync(SumForm.WS.A a1, SumForm.WS.A a2) {
            SumForm.WS.SumRequest inValue = new SumForm.WS.SumRequest();
            inValue.Body = new SumForm.WS.SumRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            return ((SumForm.WS.SimpleSoap)(this)).SumAsync(inValue);
        }
        
        public int Adds(int x, int y) {
            return base.Channel.Adds(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddsAsync(int x, int y) {
            return base.Channel.AddsAsync(x, y);
        }
    }
}
